### ISSUE TITLE
CPU usage with compositors

### ISSUE THREAD

**Issue by reyqn** [jtsiomb/xlivebg#1]
So I tried out xlivebg with the colcycle plugin and it worked as expected out of the box.
As I'm using a compositor, I used the -n option, but the CPU draw (in picom, a compton fork) was multiplied by 4.
With the -w option, I was able to use xwinwrap to use xlivebg with a compositor without the -n option, and it divided by 2 the CPU draw with picom.
I also tried with xcompmgr which is mentionned in the readme, but I have horrible tearing everywhere (CPU draw is fine though).

Right now I think the only way I can use it is without a compositor (CPU is something like 8% distributed on 8 cores), or if I find a way to fix the tearing with xcompmgr (which would be ideal)

I guess the real issues are actually in picom for the CPU issue and intel's driver for the tearing.

Anyway I just wanted to update you to say that I tried your program and it works really well, so I'll close the issue since it doesn't come from xlivebg.

**Comment by jtsiomb** [comment]
Glad to hear it worked without much hassle for you. If you figure something out that I can do to reduce any extra CPU usage when xlivebg is run under compositors, please let me know.

As a sledgehammer measure, you can tweak the `upd_interval` setting of the colcycle plugin (3rd field of the `colc_plugin` structure initializer in `plugins/colcycle/main.c` line 31, currently reads `XLIVEBG_20FPS`). It's basically how often (approximately) to update the screen in microseconds, with some common values defined in `include/xlivebg.h`, that each plugin can request according to their needs.
