### ISSUE TITLE
Video plugin build failure with ffmpeg libraries v59

### ISSUE THREAD

**Issue by Mehaafa** [jtsiomb/xlivebg#10]
vid.c: In function ‘vid_open’:
vid.c:47:17: warning: implicit declaration of function ‘av_register_all’ [-Wimplicit-function-declaration]
   47 |                 av_register_all();
      |                 ^~~~~~~~~~~~~~~
vid.c:72:41: error: ‘AVStream’ has no member named ‘codec’
   72 |                 if(vf->avctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
      |                                         ^~
vid.c:82:51: error: ‘AVStream’ has no member named ‘codec’
   82 |         vf->cctx = vf->avctx->streams[vf->vstream]->codec;
      |                                                   ^~
vid.c:84:24: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   84 |         if(!(vf->codec = avcodec_find_decoder(vf->cctx->codec_id))) {
      |                        ^
vid.c: In function ‘vid_get_frame’:
vid.c:170:25: warning: implicit declaration of function ‘avcodec_decode_video2’; did you mean ‘avcodec_decode_subtitle2’? [-Wimplicit-function-declaration]
  170 |                         avcodec_decode_video2(vf->cctx, vf->frm, &frame_done, &packet);
      |                         ^~~~~~~~~~~~~~~~~~~~~
      |                         avcodec_decode_subtitle2

Any help?

**Comment by jtsiomb** [comment]
ffmpeg has the bad habit of changing their API all the time. Could you tell me which version of ffmpeg you have installed so that I can try to reproduce the issue?

Meanwhile you can disable building the video plugin by passing `--disable-plugin-video` to the configure script.

**Comment by Mehaafa** [comment]
Yes. I am away from my PC now so I will let you know the version tomorrow. I think it is 4.4.1 but not 100% sure. Thanks.

**Comment by Mehaafa** [comment]
this is  ffmpeg version : 

ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100


And it builds fine with passing --diable-plugin-video option.
I appreciated for your help.

**Comment by jtsiomb** [comment]
I decided to remove the video plugin completely.

If someone else wants to write a better one, less processor intensive, using hardware decode and colorspace conversions where available, make it work with multiple ffmpeg versions, and maintain it as ffmpeg continuously breaks their API, please contact me.

**Comment by Hiradpi** [comment]
same build error  issue here still not fixed  

`cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include     -c -o app.o app.c
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include     -c -o image.o image.c
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include     -c -o imagelbm.o imagelbm.c
imagelbm.c:435:12: warning: ‘read16’ defined but not used [-Wunused-function]
  435 | static int read16(FILE *fp, uint16_t *res)
      |            ^~~~~~
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include     -c -o main.o main.c
cc -o colcycle.so -shared app.o image.o imagelbm.o main.o   
make[2]: Leaving directory '/home/hirad/yay/xlivebg/kos/xlivebg-1.0/plugins/colcycle'
make -C video
make[2]: Entering directory '/home/hirad/yay/xlivebg/kos/xlivebg-1.0/plugins/video'
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include  -Wno-deprecated-declarations -pthread   -c -o main.o main.c
cc -pedantic -Wall -g -O3 -ffast-math -fPIC -I../../include  -Wno-deprecated-declarations -pthread   -c -o vid.o vid.c
vid.c: In function ‘vid_open’:
vid.c:47:17: warning: implicit declaration of function ‘av_register_all’ [-Wimplicit-function-declaration]
   47 |                 av_register_all();
      |                 ^~~~~~~~~~~~~~~
vid.c:72:41: error: ‘AVStream’ has no member named ‘codec’
   72 |                 if(vf->avctx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
      |                                         ^~
vid.c:82:51: error: ‘AVStream’ has no member named ‘codec’
   82 |         vf->cctx = vf->avctx->streams[vf->vstream]->codec;
      |                                                   ^~
vid.c:84:24: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   84 |         if(!(vf->codec = avcodec_find_decoder(vf->cctx->codec_id))) {
      |                        ^
vid.c: In function ‘vid_get_frame’:
vid.c:170:25: warning: implicit declaration of function ‘avcodec_decode_video2’; did you mean ‘avcodec_decode_subtitle2’? [-Wimplicit-function-declaration]
  170 |                         avcodec_decode_video2(vf->cctx, vf->frm, &frame_done, &packet);
      |                         ^~~~~~~~~~~~~~~~~~~~~
      |                         avcodec_decode_subtitle2
make[2]: *** [<builtin>: vid.o] Error 1
`

**Comment by Hiradpi** [comment]
I know ffmpeg is mf changing api at every update but men please fix this

**Comment by jtsiomb** [comment]
Still not fixed? You're clearly using an old revision of xlivebg, so it would be surprising if that revision fixed itself while nobody was looking.
I know you're using an old revision because as I said in this thread just before your message, the video plugin has been removed. There is no video plugin in xlivebg. If anyone wishes to maintain and more importantly improve it, I'm open to reinstating it, but as it was, it only caused problems.
